/**
 * Egyptian Universities — alphabetically sorted flat list.
 * Source: universities_in_egypt.md (State-funded + National + Private merged)
 */
export const EGYPTIAN_UNIVERSITIES: string[] = [
  "Ahram Canadian University",
  "Ain Shams National University",
  "Ain Shams University",
  "Al Hayah University in Cairo",
  "Al Ryada University for Science and Technology",
  "Al Salam University in Egypt",
  "Al-Azhar University",
  "Alamein International University",
  "Alexandria National University",
  "Alexandria University",
  "Arab Academy for Science, Technology and Maritime Transport",
  "Arab Open University",
  "Assiut National University",
  "Assiut University",
  "Aswan University",
  "Badr University in Assiut",
  "Badr University in Cairo",
  "Badya University",
  "Banha University",
  "Benha National University",
  "Beni Suef National University",
  "Beni-Suef University",
  "British University in Egypt",
  "Cairo National University",
  "Cairo University",
  "Canadian International College",
  "Capital University",
  "City University of Cairo",
  "Damanhour National University",
  "Damanhour University",
  "Damietta National University",
  "Damietta University",
  "Delta University for Science and Technology",
  "Deraya University in Minya",
  "East Port Said National University",
  "Ecole Superieure Libre des Sciences Commerciales Appliquees",
  "Egypt University of Informatics",
  "Egypt-Japan University of Science and Technology",
  "Egyptian Chinese University",
  "Egyptian Russian University",
  "Egyptian e-Learning University",
  "El Saleheya El Gadida University",
  "El Sewedy University of Technology",
  "El Shorouk Academy",
  "European Universities in Egypt",
  "Fayoum National University",
  "Fayoum University",
  "French University of Egypt",
  "Future University in Egypt",
  "Galala University",
  "German International University",
  "German University in Cairo",
  "Heliopolis University",
  "Helwan National University",
  "Hertfordshire University in Egypt",
  "Horus University",
  "Innovation University",
  "Kafrelsheikh National University",
  "Kafrelsheikh University",
  "King Salman International University",
  "Lotus University in Minya",
  "Luxor National University",
  "Luxor University",
  "Mansoura National University",
  "Mansoura University",
  "May University in Cairo",
  "Memphis University",
  "Menoufia National University",
  "Menoufia University",
  "Merit University",
  "Military Technical College",
  "Minia University",
  "Minya National University",
  "Misr International University",
  "Misr University for Science and Technology",
  "Modern Sciences and Arts University",
  "Modern University for Technology and Information",
  "Nahda University",
  "National University of Sadat City",
  "New Ismailia National University",
  "New Mansoura University",
  "New Valley National University",
  "New Valley University",
  "Newgiza University",
  "Nile University",
  "Nile Valley University",
  "October 6 University",
  "Pharos University in Alexandria",
  "Port Said University",
  "Rashid University",
  "Sadat Academy for Management Sciences",
  "Saxony Egypt University",
  "Sinai University",
  "Sohag National University",
  "Sohag University",
  "South Valley National University",
  "South Valley University",
  "Sphinx University",
  "Suez Canal University",
  "Suez National University",
  "Suez University",
  "Tanta National University",
  "Tanta University",
  "The American University in Cairo",
  "The Egyptian E-learning University",
  "Toronto Metropolitan University Cairo",
  "University of Prince Edward Island",
  "University of Sadat City",
  "Zagazig National University",
  "Zagazig University",
  "Zewail City of Science, Technology and Innovation",
];

/**
 * Egyptian major cities / governorate capitals.
 */
export const EGYPTIAN_CITIES: string[] = [
  "10th of Ramadan City",
  "6th of October City",
  "Abu Simbel",
  "Al-Arish",
  "Alexandria",
  "Assiut",
  "Aswan",
  "Banha",
  "Beni Suef",
  "Cairo",
  "Damanhour",
  "Damietta",
  "El-Mahalla El-Kubra",
  "El-Minya",
  "Fayoum",
  "Giza",
  "Hurghada",
  "Ismailia",
  "Kafr el-Sheikh",
  "Luxor",
  "Mansoura",
  "Marsa Matrouh",
  "Menoufia",
  "New Cairo",
  "New Valley (Kharga)",
  "Port Said",
  "Qena",
  "Rosetta",
  "Sadat City",
  "Sharm el-Sheikh",
  "Sheikh Zayed City",
  "Shibin el-Kom",
  "Shubra el-Kheima",
  "Sohag",
  "Suez",
  "Tanta",
  "Zagazig",
];
