/**
 * Single master list of skills for filters (employer talent search, student explore)
 * and skill pickers across the app. Order here is arbitrary; UIs may sort for display.
 */
export const SKILL_CATALOG: readonly string[] = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Csharp",
  "Go",
  "Rust",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Dart",
  "React",
  "Nextjs",
  "Vue",
  "Angular",
  "Svelte",
  "HTML",
  "CSS",
  "Tailwindcss",
  "Sass",
  "Nodejs",
  "Express",
  "Django",
  "Flask",
  "Spring",
  "Laravel",
  "Rails",
  "Flutter",
  "React Native",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "GCP",
  "Git",
  "GitHub",
  "Linux",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Redis",
  "Firebase",
  "GraphQL",
  "Figma",
  "Photoshop",
  "Illustrator",
  "Blender",
  "Unity",
  "TensorFlow",
  "PyTorch",
] as const;
